vim.g.mapleader = " "

require("mappings.tree")
require("mappings.personal")
require("mappings.telescope")
require("mappings.buffer")
require("mappings.git")
require("mappings.spectre")
require("mappings.hop")
require("mappings.trouble")
require("mappings.movement")
require("mappings.copilot")
require("mappings.silicon")
require("mappings.zen")
require("mappings.dap")
require("mappings.term")
require("mappings.formatter")
require("mappings.db")
require("mappings.neotest")
