local lsp_config = require("lspconfig")
local merge = require("utils.merge")
local on_attach = require("lsp/on_attach")

local default_stubs = {
  "apache",
  "bcmath",
  "bz2",
  "calendar",
  "com_dotnet",
  "Core",
  "ctype",
  "curl",
  "date",
  "dba",
  "dom",
  "enchant",
  "exif",
  "FFI",
  "fileinfo",
  "filter",
  "fpm",
  "ftp",
  "gd",
  "gettext",
  "gmp",
  "hash",
  "iconv",
  "imap",
  "intl",
  "json",
  "ldap",
  "libxml",
  "mbstring",
  "meta",
  "mysqli",
  "oci8",
  "odbc",
  "openssl",
  "pcntl",
  "pcre",
  "PDO",
  "pdo_ibm",
  "pdo_mysql",
  "pdo_pgsql",
  "pdo_sqlite",
  "pgsql",
  "Phar",
  "posix",
  "pspell",
  "readline",
  "Reflection",
  "session",
  "shmop",
  "SimpleXML",
  "snmp",
  "soap",
  "sockets",
  "sodium",
  "SPL",
  "sqlite3",
  "standard",
  "superglobals",
  "sysvmsg",
  "sysvsem",
  "sysvshm",
  "tidy",
  "tokenizer",
  "xml",
  "xmlreader",
  "xmlrpc",
  "xmlwriter",
  "xsl",
  "Zend OPcache",
  "zip",
  "zlib",
  "random",
}

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

require("lspconfig").intelephense.setup({
  on_init = function(client)
    client.server_capabilities.documentFormattingProvider = false
  end,
  format = {
    enable = true,
  },
  settings = {
    intelephense = {
      stubs = merge(default_stubs, {
        "mongodb",
      }),
    },
  },
  capabilities = capabilities,
  on_attach = on_attach,
})
