[opener]
edit = [
	{ run = '${EDITOR:=nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'code "%*"',    orphan = true, desc = "code",         for = "windows" },
	{ run = 'code -w "%*"', block = true,  desc = "code (block)", for = "windows" },
]
