#!/usr/bin/env sh

# stop process new window manager in Ventura
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config \
	layout stack \
	top_padding 0   \
	bottom_padding 0  \
	left_padding 0 \
	right_padding 0

yabai -m config window_shadow off
yabai -m config external_bar all:35:0

# Address issue windows of manage=off applications always in foreground
yabai -m rule --add app=".*" sub-layer=normal

# signals

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Telegram Web" manage=off
yabai -m rule --add app="Telegram" manage=off
yabai -m rule --add app="Preview" manage=off
yabai -m rule --add app="Spotify" manage=off
yabai -m rule --add app="OrbStack" manage=off
yabai -m rule --add app="Obsidian" manage=off
yabai -m rule --add app="Zalo" manage=off
yabai -m rule --add app="Mail" manage=off
yabai -m rule --add app="^DataGrip$" manage=off

# open Alacritty in space 2
# yabai -m rule --add app="Alacritty" space=2

sudo yabai --load-sa

echo "yabai configuration loaded.."
